### ISSUE TITLE
update to zplsc_b code?

### ISSUE THREAD

**Issue by leewujung** [oceanobservatories/mi-instrument#34]
Hi, I am wondering if you'll be interested in user submitting changes to code for specific instruments. I've been working on zplsc_b data and added additional functions to allow calibration of the power data unpacked from .raw in my fork. I am using the fork as a submodule in my other repo now, but wonder what is the preferred path forward. Also wondering what license the code is under, I saw a license file in the top level but the zplsc_b code uses Apache 2.0? Thanks!

**Comment by danmergens** [comment]
Community submitted updates are welcome. If you submit code it should be under the Apache 2.0 or GNU General Public License 3.0.
